title: Mind to Matter
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:title/
timezone: 'America/Chicago'
strict_front_matter: true
sass:
  sass_dir: '_sass'
  style: 'compressed'