name: 'Zero Barrier'
description: 'Our mission is to reduce the barriers to mass production to zero, by establishing a metal 3D printing factory filled with our proprietary printers.'
email: 'contact@zerobarrierlabs.com'
author: 'Evan Wolfenden'
url: "https://zerobarrierlabs.com"
permalink: /:year/:title/
timezone: 'America/Chicago'
strict_front_matter: true
sass:
  sass_dir: '_sass'
  style: 'compressed'
production: false